server:
  port: 7090 # 应用服务 WEB 访问端口
  servlet:
    context-path: /api
    session:
      timeout: PT60M #session过期时间 60M 一个小时
#处理favicon
spring:
  mvc:
    favicon:
      enable: false
#    throw-exception-if-no-handler-found: true #错误页处理
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#   邮箱
  mail:
    host: smtp.qq.com
    port: 465
    username: 1622006863@qq.com
    password: zepfmpgtjvgwjieb
    default-encoding: UTF-8
    properties:
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.debug: true
#    redis
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 2000

project:
  folder: d:/tmp/webser/myapps/easypan/

log:
  root:
    level: info

admin:
  emails: test@qq.com

dev: false

qq:
  app:
    id: 123456
    key: 123456
  url:
    authorization: "https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s"
    access:
      token: "https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s"
    openid: "https://graph.qq.com/oauth2.0/me?access_token=%S"
    user:
      info: "https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s"
    redirect: "http://easypan.wuhancoder.com/qqlogincalback"